name: release-electron
on:
  workflow_call:
    inputs:
      VERSION:
        required: false
        type: string
        description: 'Application version'
        default: ${{ github.event.release.tag_name }}
    secrets:
      GH_TOKEN:
        description: "Github Token"
        required: true

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package Application
        run: npm run package

      - name: compress artifact
        id: compress
        uses: alvarogarciapiz/Actions/compress-files@main
        with:
          ORIGIN_PATH: "./dockerboard-darwin-arm64"
          NAME: "dockerboard_app_macOS_${{ inputs.VERSION }}"
          COMPRESSION: "zip"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress.outputs.FILE_PATH }}
          asset_name: dockerboards.zip
          asset_content_type: application/zip
  
  prepare-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package Application
        run: npm run package
      
      - name: Stash artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockerboard-win32-x64
          path: "./dockerboard-win32-x64"

  build-win:
    runs-on: ubuntu-latest
    needs: prepare-win
    steps:
      - name: Unstash artifact
        uses: actions/download-artifact@v4
        with:
          name: dockerboard-win32-x64

      - name: compress artifact
        id: compress
        uses: alvarogarciapiz/Actions/compress-files@main
        with:
          ORIGIN_PATH: "./dockerboard-win32-x64"
          NAME: "dockerboard_app_macOS_${{ inputs.VERSION }}"
          COMPRESSION: "zip"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress.outputs.FILE_PATH }}
          asset_name: dockerboards.zip
          asset_content_type: application/zip
